<?php echo $this->partial('user/header.phtml' );?>
<style>
    input{
        width:90% !important;
    }
    td{
        padding-bottom: 20px;
    }
    h1{
        margin-bottom: 50px;
        
    }
    #submit{
        margin-top: 50px;
        height:56px;
        font-size:30px;
    }
    .jumbotron{
        width: 50%;
        margin-left: 342px;
        border-radius: 210px;
    }
    .jumbotron h1{
        font-size: 48px;
    }
    
</style>
<div class="jumbotron" align="center">
    <h1> Edit Category </h1>
<?php



if($this->admin){
echo $this->form;
}
?>

</div>


