
<br /><br />
<div id="view-content">
	<p>View script for controller <b>category</b> and script/action name <b>getCategory</b></p>
</div>

<?php
//$this->form->setAction($this->url());

//var_dump($this->categories);

?>
           
<script>

        ajaxRequest = new XMLHttpRequest();
function ajax(url){
           ajaxRequest.open("GET","http://localhost/zend_project/public/" + url, true);
           ajaxRequest.send();
        }
        ajaxRequest.onreadystatechange = function(){    
                     
        if(ajaxRequest.readyState ===4 && ajaxRequest.status===200){
            response=(ajaxRequest.responseText);
            document.getElementById('row'+response).parentNode.removeChild(document.getElementById('row'+response));
         }
        };


        ajaxRequestedit = new XMLHttpRequest();
function editwithajax(url){
           document.getElementById('catName'+response).parentNode.removeChild(document.getElementById('catName'+response));
           ajaxRequestedit.open("GET","http://localhost/zend_project/public/" + url, true);
           ajaxRequestedit.send();
        }
        ajaxRequestedit.onreadystatechange = function(){    
                     
        if(ajaxRequestedit.readyState ===4 && ajaxRequestedit.status===200){
            response=(ajaxRequestedit.responseText);
            document.getElementById('row'+response).parentNode.removeChild(document.getElementById('row'+response));
         }
        };




</script>


<table class="DataTable tablesorter" width="100%" valign="top" align="center" border="0" cellpadding="2" cellspacing="2" width="100%">  
    <thead>
        <tr>
            
                <?php foreach ( $this->categories[0] as $key =>$value) { ?> 
                    <th><?php echo ($key); ?></th> 
                <?php }?> 
        </tr>
    </thead>
    <tbody>
    <?php $i=0;
        echo "<a href=".'http://localhost/zend_project/public/Category/addcategory'.">add category</a>";
        foreach ( $this->categories as $category) { ?>
        <tr <?php echo "id='row".$category['catId']."'";?>> 
            
        
        <td <?php echo "id='catName".$category['catId']."'";?>>
          <?php      echo $category['catName'].'&nbsp;';?>
        
        </td>
        
             
        <td>
        <?php
echo "<td>"."<input value='delete' type='button'  id='".$category['catId']."' onclick =ajax('Category/deletecategory?catId=".$category['catId']."') >";  
echo "</td>"; 
?>    
        </td> 
        <td>
        <?php
echo "<td>"."<input value='edit' type='button'  id='".$category['catId']."' onclick =editwithajax('Category/editcategory?catId=".$category['catId']."') >";  
echo "</td>";        
?>
           
        
        </tr> 


        <?php  
        $forums=$this->forums[$i];

        foreach ($forums  as $forum) { ?>
        <tr <?php echo "id='row".$forum['forumId']."'";?>>
         <td>
        <?php

          echo "<a href=".'http://localhost/zend_project/public/Forum/forumdata?forumId='.$forum['forumId'].">".$forum['forumName']."</a>" ;
        ?>    
        </td>        
          <?php
echo "<td>"."<input value='delete' type='button'  id='".$forum['forumId']."' onclick =ajax('Forum/deleteforum?forumId=".$forum['forumId']."') >";  
echo "</td>";        
?>
        
        </tr>    
    <a href="get-category.phtml"></a>
        <?php }?>
              
        <?php $i=$i+1; }?>                            
    </tbody>
</table>

