
<br /><br />
<div id="view-content">
	<p>View script for controller <b>category</b> and script/action name <b>getCategory</b></p>
</div>

<?php
//$this->form->setAction($this->url());

//var_dump($this->categories);

?>
           
<script>

        ajaxRequest = new XMLHttpRequest();
function ajax(url){
           ajaxRequest.open("GET","http://localhost/zend_project/public/" + url, true);
           ajaxRequest.send();
        }
        ajaxRequest.onreadystatechange = function(){    
                     
        if(ajaxRequest.readyState ===4 && ajaxRequest.status===200){
            response=(ajaxRequest.responseText);
            alert(response);
            document.getElementById('row'+response).parentNode.removeChild(document.getElementById('row'+response));
         }
        };

        ajaxRequestLock = new XMLHttpRequest();
function ajaxlock(url,id){
           
           ajaxRequestLock.open("GET","http://localhost/zend_project/public/" + url, true);
           ajaxRequestLock.send();
        
        ajaxRequestLock.onreadystatechange = function(){    
                     
        if(ajaxRequestLock.readyState ===4 && ajaxRequestLock.status===200){
            response=(ajaxRequestLock.responseText);
            $lockbtn=document.getElementById('lbtn'+id); 
            if(response){response="unlock";}
            else{response="lock"}
            $lockbtn.setAttribute("value",response);
            
        }
        };
    }
</script>


<table class="DataTable tablesorter" width="100%" valign="top" align="center" border="0" cellpadding="2" cellspacing="2" width="100%">  
    <thead>
        <tr>
            
                <?php foreach ( $this->categories[0] as $key =>$value) { ?> 
                    <th><?php echo ($key); ?></th> 
                <?php }?> 
        </tr>
    </thead>
    <tbody>
    <?php $i=0;
        echo "<a href=".'http://localhost/zend_project/public/Category/addcategory'.">add category</a>";
        foreach ( $this->categories as $category) { ?>
        <tr <?php echo "id='row".$category['catId']."'";?>> 
            
        
        <td <?php echo "id='catName".$category['catId']."'";?>>
          <?php echo "<a href=".'http://localhost/zend_project/public/Category/categorydata?categoryId='.$category['catId']."&categoryName='".$category['catName']."'>".$category['catName']."</a>" ;
        ?>
        
        </td>
        
             
        <td>
        <?php
   
       if($this->myInfo->isAdmin){
echo "<td>"."<input value='delete' type='button'  id='".$category['catId']."' onclick =ajax('Category/deletecategory?catId=".$category['catId']."') >";  
echo "</td>"; 
?>    
        </td> 
        <td>
        <?php
          echo "<a href=".'http://localhost/zend_project/public/Category/editcategory?categoryId='.$category['catId']."&categoryName='".$category['catName']."'>".'edit'.$category['catName']."</a>" ;
       
        ?>
        
            <?php
echo "<td>"."<input value='";
if($category['catIsLocked']){echo 'unlock';}else{echo 'lock';} 
echo "' type='button'  id='lbtn".$category['catId']."' onclick = \" ajaxlock('Category/lockcategory?catId=".$category['catId']."&forumLock=".$category['catIsLocked']."' ,".$category['catId'].")\" >";  
echo "</td>";        

?>
        
        </tr> 


        <?php  
        $forums=$this->forums[$i];
        
        for($in=0 ; ($in<3 && $in<count($forums)) ; $in++){    
        //foreach ($forums  as $forum) { 
         
        ?>
        <tr <?php echo "id='row".$forums[$in]['forumId']."'";?>>
         <td>
        <?php
        
echo "<a href=".'http://localhost/zend_project/public/Forum/forumdata?forumId='.$forums[$in]['forumId'].">".$forums[$in]['forumName']."</a>" ;
       
        ?>    
        </td>        
          <?php
//echo "<td>"."<input value='delete' type='button'  id='".$forum['forumId']."' onclick =ajax('Forum/deleteforum?forumId=".$forum['forumId']."') >";  
//echo "</td>";        
?>
        
        </tr>    
   
        <?php } ?>
              
       <?php $i=$i+1; }}?>                            
    </tbody>
</table>

