<?php echo $this->partial('user/header.phtml' );?>


<script src="http://localhost/zend_project/public/media/js/user/listusers.js" ></script>



<?php
//$this->form->setAction($this->url());

//var_dump($this->categories);

if (!$this->myInfo)
{
    $isadmin = NULL;
}
else{
    $isadmin = $this->myInfo->isAdmin;
}

?>
           
<script>

        ajaxRequest = new XMLHttpRequest();
function ajax(url){
           ajaxRequest.open("GET","http://localhost/zend_project/public/" + url, true);
           ajaxRequest.send();
        }
        ajaxRequest.onreadystatechange = function(){    
                     
        if(ajaxRequest.readyState ===4 && ajaxRequest.status===200){
            response=(ajaxRequest.responseText);
             var forums = document.getElementsByClassName('row'+response);
             
             
             
           
            for (i = 0; i < (forums.length); i++) {
             forums[i].remove();
             
             }
             forums = document.getElementsByClassName('row'+response)[0];
             if(forums){
              forums.remove();}
 
             
            document.getElementById('row'+response).parentNode.removeChild(document.getElementById('row'+response));
            
         }
        };

        ajaxRequestLock = new XMLHttpRequest();
function ajaxlock(url,id){
           
           ajaxRequestLock.open("GET","http://localhost/zend_project/public/" + url, true);
           ajaxRequestLock.send();
        
        ajaxRequestLock.onreadystatechange = function(){    
                     
        if(ajaxRequestLock.readyState ===4 && ajaxRequestLock.status===200){
            response=(ajaxRequestLock.responseText);
            $lockbtn=document.getElementById('lbtn'+id); 
            if(response){response="unlock";}
            else{response="lock"}
            $lockbtn.setAttribute("value",response);
            
            $lockbtn.firstChild.data=response;
        }
        };
    }
</script>


<table  class="table table-hover" width="100%" valign="top" align="center" border="0" cellpadding="2" cellspacing="2" width="100%">  
    <thead>
        <tr>
            
                
                    <th><?php echo ("Category Name"); ?></th> 
             
        </tr>
    </thead>
    <tbody>
    <?php $i=0;
        if($isadmin){
         echo "<label style='margin-left: 1113px;font-size: 24px;'><a href=".'http://localhost/zend_project/public/Category/addcategory'.">+add category</a></label>";
         
        }
         foreach ( $this->categories as $category) { ?>
        <tr  <?php echo "id='row".$category['catId']."'";?>> 
            
        
        <td class="danger" <?php echo "id='catName".$category['catId']."'";?>>
          <?php echo "<a  style='font-size:30px'; href=".'http://localhost/zend_project/public/Category/categorydata?categoryId='.$category['catId']."&categoryName='".$category['catName']."'>".$category['catName']."</a>" ;
        ?>
        
        </td>
        
             
        <td>
        <?php
   
       if($isadmin){
echo "<td>"."<button class='btn btn-lg btn-danger' value='delete' id='".$category['catId']."' onclick =ajax('Category/deletecategory?catId=".$category['catId']."')>"."delete"."</button>";  
echo "</td>"; 
?>    
        </td> 
        <td>
        <?php
          echo "<a href=".'http://localhost/zend_project/public/Category/editcategory?categoryId='.$category['catId']."&categoryName='".$category['catName']."'>".'<button class="btn btn-lg btn-default">'.'edit   '.'</button>'."</a>" ;
       
        ?>
        
            <?php
echo "<td>"."<button class='btn btn-lg btn-success' ";
echo " id='lbtn".$category['catId']."' value=\"";
if($category['catIsLocked']){echo 'unlock';}else{echo 'lock';};
echo "\" onclick = \" ajaxlock('Category/lockcategory?catId=".$category['catId']."&forumLock=".$category['catIsLocked']."' ,".$category['catId'].")\" >";  

if($category['catIsLocked']){echo 'unlock';}else{echo 'lock';} 
echo "</button></td>";        
       }
?>
        
        </tr> 


        <?php  
        $forums=$this->forums[$i];
        
        for($in=0 ; ($in<3 && $in<count($forums)) ; $in++){    
        //foreach ($forums  as $forum) { 
         
        ?>
        <tr <?php echo "id='row".$forums[$in]['forumId']."' class='row".$category['catId']."'";?>>
         <td>
        <?php
        
echo "<a href=".'http://localhost/zend_project/public/Forum/forumdata?forumId='.$forums[$in]['forumId'].">".$forums[$in]['forumName']."</a>" ;
       
        ?>    
        </td>        
          <?php
//echo "<td>"."<button class='btn btn-lg btn-danger'><input  value='delete' type='button'  id='".$forum['forumId']."' onclick =ajax('Forum/deleteforum?forumId=".$forum['forumId']."') ></button>";  
//echo "</td>";        
?>
        
        </tr>    
   
        <?php } ?>
              
       <?php $i=$i+1; }?>                            
    </tbody>
</table>
