<?php echo $this->partial('user/header.phtml' );?>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

<style>
    img{
        width:140px;
        height:140px;
    }
    input{
        width:60% !important;
    }
    .pp{
       margin-left: 782px;
        margin-top: -450px;
        width: 20%;
        height: 30%;
    }
    td{
        padding: 9px;
    }
    .s{
        margin-left: 782px;
        margin-top: -151px;
    }
</style>


<br /><br />

<div class='container'>
    <div id="view-content">
        <?php
        if ($this->message)
            echo "<p> <b> " . $this->message . "</b></p></div>";
        ?>


    </div>
    <div class="form-group">
        <?php
          
        echo $this->form;
        if($this->image){
        $img = '/zend_project/public/media/images/' . $this->image;
        echo "<img class='img-rounded pp' src ='$img' >";
        }
      
        
        $profpic = '/zend_project/public/media/profile/' . $this->profpic;
        echo "<img class='img-rounded s' src ='$profpic' >";
        ?>
    </div>
</div >