<?php echo $this->partial('user/header.phtml' );?>



<style>
   #view-content{
        border: medium solid;
        border-color: red;
        background-color: pink;
        width: 900px;
        text-align: center;
        padding-top: 45px;
        padding-bottom: 45px;
        margin-left: 192px;
    }
</style>  
<br /><br />
<div id="view-content">
    The page you requested not exists or might be broken.   
</div>