<!DOCTYPE html>
<?php
         $front = Zend_Controller_Front::getInstance();
         $bootstrap = $front->getParam("bootstrap"); 
         $myInfo = $bootstrap->myinfo; 
        /*if($authorization->hasIdentity()) {
             $info = $authorization->getIdentity();
             
        }*/


?>

<html lang="en">
<head>
  <title>Bootstrap Case</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
 <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/media/css/bootstrap.3.2.0.css.bootstrap.min.css">
 <script src="<?php echo $this->baseUrl();?>/media/jquery/ajax.googleapis.jquery.min.js"></script>
 <script src="<?php echo $this->baseUrl();?>/media/jquery/js.3.2.0.bootstrap.min.js"></script>
 <style>
     body {
         background-color: #CCCC99;
         background-image: url('<?php echo $this->baseUrl(); ?>/media/images/bgflower.jpg') !important;
         background-repeat: no-repeat;
         background-size: cover;
     }
 </style>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<?php echo $this->baseUrl();?>/category/getcategory">Ftakat</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="<?php echo $this->baseUrl();?>/category/getcategory">Home</a></li>
    
    <?php if ( isset($myInfo) && $myInfo->isAdmin) { ?>

        <li><a href="<?php echo $this->baseUrl();?>/system/showsystem">System</a></li>
        <li><a href="<?php echo $this->baseUrl();?>/user/listusers">Users</a></li>
    <?php }   ?>
      </ul>
      <ul class="nav navbar-nav navbar-right">
       <?php if ($myInfo == NULL) { ?>
            <li><a href=<?php echo $this->baseUrl()."/user/register" ?>><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href=<?php echo $this->baseUrl()."/user/login" ?>><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
       <?php  
       }else{ ?>
        <li><a href= <?php echo $this->baseUrl()."/user/edit/id/".$myInfo->id;?>><span class="glyphicon glyphicon-user"></span> Profile</a></li>
        <li><a href=<?php echo $this->baseUrl()."/user/logout" ?>><span class="glyphicon glyphicon-log-in"></span> Log Out</a></li>
       <?php } ?>         
      </ul>
    </div>
  </div>
</nav>
  


</body>
</html>
