<style>
    img{
        width:70px;
        height:70px;
    }
    
    button {
        margin: 5px !important;
        padding:8px !important;
        font-size: 16px !important;
    }
</style>




<?php echo $this->partial('user/header.phtml' );?>

<script src="http://localhost/zend_project/public/media/jquery/ajax.googleapis.jquery.min.js"></script>
<script src="http://localhost/zend_project/public/media/js/user/listusers.js" ></script>
<!--<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">-->


<?php


    
     echo "<div class='col-md-12'><table class='table table-striped'>";
     
     echo "<th>ID</th><th>Username</th><th>Password</th><th>Email</th><th>Gender</th><th>Status</th>"
     . "<th>Country</th><th>Profile picture</th><th>Signature</th><th>Actions</th>";
     
    foreach ($this->users as $user){
        
        echo "<tr id='".$user['id']."' >";
        echo "<td> ".$user['id'] ."</td>";
        echo "<td> ".$user['username'] ."</td>";
        echo "<td> ".$user['password'] ."</td>";
        echo "<td> ".$user['email'] ."</td>";

        echo "<td> ".$user['gender'] ."</td>";
        echo "<td> ".$user['status'] ."</td>";
        echo "<td> ".$user['country'] ."</td>";
        echo "<td><img src='/zend_project/public/media/profile/".$user['profpic'] ."' ></td>";
        echo "<td><img src='/zend_project/public/media/images/".$user['signature'] ."' ></td>";
        echo "<td><button  class='btn btn-lg btn-danger' onclick='deleteUser(this)' >Delete</button>";

        
        
        if ($user['isAdmin'])
            echo "<button onclick='Edit(this)' class='btn btn-lg btn-default'  >Edit</button><button class='btn btn-lg btn-default' onclick='makeAdmin(this)'>Make normal user</button>";
        else
            
            echo "<button onclick='Edit(this)' class='btn btn-lg btn-default' >Edit</button><button class='btn btn-lg btn-default' onclick='makeAdmin(this)'>Make admin</button>";
        
        
        if (!$user['isBan'] && !$user['isAdmin']) {
        echo "<button class='btn btn-lg btn-danger'  onclick='ban(this)'>Ban user</button>";
    } elseif (!$user['isAdmin']) {
        echo "<button   class='btn btn-lg btn-success' onclick='ban(this)'>Unban user</button>";
    }
    echo "</td></tr>";
      
    }
    echo "</table></div> ";


?>