<?php echo $this->partial('user/header.phtml' );?>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<style>
    input{
        width:90% !important;
    }
    td{
        padding-bottom: 20px;
    }
    h1{
        margin-bottom: 50px;
    }
    #submit{
        margin-top: 50px;
        height:70px;
        font-size:30px;
    }
    margin
</style>
<div class="jumbotron" align="center">
        
    
  
<h1> Sign In </h1>
<div id="view-content" class="form-group" >
	
<?php
if (isset($this->message)) echo $this->message;;
echo $this->form;
?>
    forget password?<a href="<?php echo $this->baseUrl()?>/user/forgetpassword" >forgot password</a><br/>
Not a member?<a href="<?php echo $this->baseUrl()?>/user/register" >Sign up!</a>
</div>
</div>