<?php echo $this->partial('user/header.phtml' );?>

<style>
    input{
        width:90% !important;
    }
    label{
        float:left;
    }
    td{
        padding-bottom: 20px;
    }
    h1{
        margin-bottom: 50px;
    }
    #submit{
        margin-top: 50px;
        height:70px;
        font-size:30px;
    }
    
</style>
<br /><br />
<div class="container">
  <div class="jumbotron" align="center">
        
    
  
<h1> Sign Up </h1>
<div id="view-content" class="form-group" >
	
        
<?php
echo $this->form;
?>
</div>
</div>

  
</div>