<?php echo $this->partial('user/header.phtml' );?>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<style>
    input{
        width:90% !important;
    }
    td{
        padding-bottom: 20px;
    }
    h1{
        margin-bottom: 50px;
        
    }
    #submit{
        margin-top: 50px;
        height:56px;
        font-size:30px;
    }
    .jumbotron{
        width: 50%;
        margin-left: 342px;
        border-radius: 210px;
    }
    .jumbotron h1{
        font-size: 48px;
    }
    
</style>
<div class="jumbotron" align="center">
    <h1> enter your password </h1>
<?php
        if ($this->message)
            echo "<p> <b> " . $this->message . "</b></p></div>";
        ?>
<?php

echo $this->form;

?>

</div>
