<?php echo $this->partial('user/header.phtml' );?>


<style>
   #view-content{
        border: medium solid;
        border-color: red;
        background-color: pink;
        width: 900px;
        text-align: center;
        padding: 45px 0px;
        margin-left: 192px;
    }
</style>    
<br /><br />
<div id="view-content" >
        Sorry, an error occurred and the system is now closed. We are notified and will fix it.
</div>