
<script src="http://localhost/zend_project/public/media/js/system/showsystem.js" ></script>


<br /><br />
<div id="view-content">
    <table><tr>
            <th>Status</th>
            <th>Last change by</th>
        </tr><tr>
            
            
<?php
 
if ($this->status == 0){
    echo "<td><button id='".$this->myInfo->id."' onclick='system(this)'>Open System</button></td>";   
}else{
    echo "<td><button id='".$this->myInfo->id."'  onclick='system(this)'>Close System</button></td>";   
}


echo "<td>".$this->adminname."</td>"; 
 
 
 
?>
        </tr></table>
</div>